# This file contains the paths to the various original model implementations which are wrapped in this project.

[monodepth2]
    root = '/tmp/monodepth2/'

[mvsnet_pl]
    root = '/tmp/mvsnet_pl'

[vis_mvsnet]
    root = '/misc/student/barkes/Vis-MVSNet'
    
[midas]
    root = '/tmp/midas'
